In [1]:
import pandas as pd

C:\Users\A200162055\Miniconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [15]:
df = pd.read_csv('../data/raw/spotify_2023.csv', encoding='latin-1')
print(f'The dataframe consists of {len(df)} rows and {len(df.columns)} columns.')

The dataframe consists of 953 rows and 24 columns.

In [21]:
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [4]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

In [6]:
col = "streams"

df[col] = pd.to_numeric(df[col], errors="coerce")
df[col] = df[col].astype('Int64')

num_invalid = df[col].isna().sum()
if num_invalid > 0:
    print(f"Warning: {num_invalid} invalid entries found in column '{col}' and set to NaN.")

Warning: 1 invalid entries found in column 'streams' and set to NaN.

In [7]:
col = 'in_shazam_charts'
df[col] = df[col].str.replace(',', '', regex=False)
df[col] = pd.to_numeric(df[col], errors='coerce')
df[col] = df[col].astype('Int64')

num_invalid = df[col].isna().sum()
if num_invalid > 0:
    print(f'Warning: {num_invalid} invalid entries found in column {col} and set to NaN.')

Warning: 50 invalid entries found in column in_shazam_charts and set to NaN.

In [8]:
col = 'in_deezer_playlists'
df[col] = df[col].str.replace(',', '', regex=False)
df[col] = pd.to_numeric(df[col], errors='coerce')
df[col] = df[col].astype('Int64')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               952 non-null    Int64
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    Int64
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    Int64
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: Int64(3), int64(17), object(4)
memory usage: 181.6+ KB

In [10]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,952.0,953.000000,953.000000,953.0,953.000000,903.0,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,514137424.939076,67.812172,51.908709,385.187828,2.666317,59.99557,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,566856949.038883,86.441493,50.630241,1130.535561,6.035599,161.161093,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,2762.0,0.000000,0.000000,0.0,0.000000,0.0,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,141636175.0,13.000000,7.000000,13.0,0.000000,0.0,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,290530915.0,34.000000,38.000000,44.0,0.000000,2.0,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,673869022.0,88.000000,87.000000,164.0,2.000000,37.0,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,3703895074.0,672.000000,275.000000,12367.0,58.000000,1451.0,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [11]:
group_cols = ['track_name', 'artist(s)_name']

duplicates_mask = df.duplicated(subset=group_cols, keep=False)
duplicate_rows = df[duplicates_mask]
duplicate_rows

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
178,SNAP,Rosa Linn,1,2022,3,19,3202,18,726307468,148,...,170,NaN,Major,56,53,64,11,0,45,6
345,SPIT IN MY FACE!,ThxSoMch,1,2022,10,31,629,14,303216294,32,...,94,G#,Major,73,65,79,5,2,11,6
372,About Damn Time,Lizzo,1,2022,7,15,2332,2,723894473,0,...,109,A#,Minor,84,72,74,10,0,34,7
482,SPIT IN MY FACE!,ThxSoMch,1,2022,10,31,573,0,301869854,1,...,166,C#,Major,70,57,57,9,20,11,7
512,Take My Breath,The Weeknd,1,2021,8,6,2597,0,130655803,17,...,121,A#,Minor,70,35,77,1,0,26,4
616,Take My Breath,The Weeknd,1,2021,8,6,6392,0,432702334,174,...,121,G#,Major,75,53,74,2,0,11,5
764,About Damn Time,Lizzo,1,2022,4,14,9021,0,723894473,242,...,109,A#,Minor,84,72,74,10,0,34,7
873,SNAP,Rosa Linn,1,2022,3,19,1818,0,711366595,3,...,170,NaN,Major,56,52,64,11,0,45,7

In [12]:
sum_cols = ['in_spotify_playlists', 'streams', 'in_apple_playlists', 'in_deezer_playlists', ]
avg_cols = ['artist_count', 'released_year', 'released_month', 'released_day', 'in_spotify_charts', 'in_apple_charts', 'in_deezer_charts', 'in_shazam_charts', 'bpm', 'danceability_%', 'valence_%', 'energy_%', 'acousticness_%', 'instrumentalness_%', 'speechiness_%', 'liveness_%']
first_cols = ['key', 'mode']

In [13]:
agg_dict = {col: 'sum' for col in sum_cols}
agg_dict.update({col: 'mean' for col in avg_cols})
agg_dict.update({col: 'first' for col in first_cols})

df_aggregated = df.groupby(group_cols).agg(agg_dict).reset_index()

for col in avg_cols:
    df_aggregated[col] = df_aggregated[col].round().astype('Int64')

In [15]:
df_aggregated

,track_name,artist(s)_name,in_spotify_playlists,streams,in_apple_playlists,in_deezer_playlists,artist_count,released_year,released_month,released_day,...,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,speechiness_%,liveness_%,key,mode
0,'Till I Collapse,"Eminem, Nate Dogg",22923,1695712020,78,2515,2,2002,5,26,...,171,55,10,85,7,0,20,8,C#,Major
1,(It Goes Like) Nanana - Edit,Peggy Gou,2259,57876440,0,109,1,2023,6,15,...,130,67,96,88,12,19,4,8,G,Minor
2,10 Things I Hate About You,Leah Kate,1301,185550869,23,15,1,2022,3,23,...,154,54,45,79,1,0,5,17,G#,Major
3,10:35,"TiÃ¯Â¿Â½Ã¯Â¿Â½sto, Tate M",4942,325592432,190,147,2,2022,11,1,...,120,70,70,79,7,0,10,18,G#,Major
4,2 Be Loved (Am I Ready),Lizzo,3682,247689123,41,158,1,2022,7,14,...,156,72,92,77,9,0,11,8,G,Major
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,you broke me first,Tate McRae,6638,1180094974,167,318,1,2020,4,17,...,124,64,8,37,79,0,5,9,E,Major
945,Ã½Ã½Ã½98 Braves,Morgan Wallen,282,56533272,6,0,1,2023,3,3,...,142,49,48,67,10,0,3,26,D,Major
946,Ã½Ã½Ã½abcdefu,Gayle,7215,1007612429,170,575,1,2021,8,13,...,122,70,42,54,30,0,5,37,E,Major
947,Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½,YOASOBI,356,143573775,35,8,1,2023,4,12,...,166,57,84,94,11,0,9,37,C#,Major
948,Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½Ã½,Fujii Kaze,685,403097450,24,9,1,2020,5,20,...,158,60,52,76,17,0,5,19,F#,Minor